export const ADD_POST = "ADD_POST";
export const LOAD_POSTS = "LOAD_POSTS";
export const CLEAR_POSTS = "CLEAR_POSTS";
export const LOAD_POSTS_FULFILLED = "LOAD_POSTS_FULFILLED";
export const LOAD_PUBLIC_POSTS = "LOAD_PUBLIC_POSTS";
export const LOAD_PUBLIC_POSTS_FULFILLED = "LOAD_PUBLIC_POSTS_FULFILLED";
export const UPDATE_POST = "UPDATE_POST";
export const PROGRESS_ADD_POST = "progress:ADD_POST";

export const UPLOAD_POST_STARTED = "UPLOAD_POST_STARTED";
export const UPLOADED_POST_CHUNK = "UPLOADED_POST_CHUNK";
export const UPLOAD_START = "UPLOAD_START";
export const UPLOADED_CHUNK = "UPLOAD_CHUNK";
export const UPLOAD_END = "UPLOAD_END";

export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const LOAD_POST_LIST = "LOAD_POST_LIST";
export const LOAD_APP = "LOAD_APP";

export const LOAD_PROFILE = "LOAD_PROFILE";
export const LOAD_PROFILE_FULFILLED = "LOAD_PROFILE_FULFILLED";